language: julia
sudo: required
os:
  - linux
julia:
  - 1.1
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate(); Pkg.build("Cairo")'
        - julia --project=docs/ docs/make.jl
      after_success: skip